name: ConversationStitcher
targets:
  ConversationStitcher:
    type: application
    platform: iOS
    deploymentTarget: "18.2"
    bundleId: com.example.ConversationStitcher
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ConversationStitcher
        PRODUCT_NAME: ConversationStitcher
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
    sources:
      - path: "."
